### ISSUE TITLE
请教一下部署的问题

### ISSUE THREAD

**Issue by wanglao888** [assimon/ai-anti-bot#1]
1.群组id填写完以后，机器人没有生效（已经设置管理员），请问是填写这个群组id吗 ：
![image](https://github.com/user-attachments/assets/a34c2e5f-c27f-40a1-8360-58f2b9df7ef1)
2.openai的第三方代理域名格式是什么

比如以下三种：

https://api.api.io/

https://api.api.io

api.lightai.io

感谢大佬的开源，烦请解答疑问

**Comment by assimon** [comment]
> 1.群组id填写完以后，机器人没有生效（已经设置管理员），请问是填写这个群组id吗 ： ![image](https://private-user-images.githubusercontent.com/166379526/358852215-a34c2e5f-c27f-40a1-8360-58f2b9df7ef1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxMTc4ODUsIm5iZiI6MTcyNDExNzU4NSwicGF0aCI6Ii8xNjYzNzk1MjYvMzU4ODUyMjE1LWEzNGMyZTVmLWMyN2YtNDBhMS04MzYwLTU4ZjJiOWRmN2VmMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMFQwMTMzMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NDNmOGRhMGI5OWI0YWMxYTUzZjAzZThhNGU2OGFiY2MzYjZkOTlmY2I5ODM3ZDRmNjQ2MTRkMTczNTFmNDNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.N5EECpLx0-DhYUCxG4EgGr0x8_sOrGSR42Mg1sVPWA0) 2.openai的第三方代理域名格式是什么
> 
> 比如以下三种：
> 
> https://api.api.io/
> 
> https://api.api.io
> 
> api.lightai.io
> 
> 感谢大佬的开源，烦请解答疑问

1. 需要填写群组id
2. 每家中转api不同，可尝试以下方式
https://api.api.io/
https://api.api.io/v1
具体看中转站的说明
