### ISSUE TITLE
求教怎么部署

### ISSUE THREAD

**Issue by thofith** [assimon/ai-anti-bot#3]
2024年11月16日上午：
在虚拟机ubuntu系统中安装了docker compose，目前一直卡在“无法找到镜像”，添加国内镜像到daemon.json也不行；
虚拟机通过桥接可以连外网，docker info显示桥接配置也正确。但docker run hello-world一直提示找不到镜像。
2024年11月16日18:00
更换了新的镜像链接，成功运行，但是又有新问题：一直提示
telebot: Post "https://api.telegram.org/bot7**************/getMe": dial tcp 199.96.63.53:443: i/o timeout
![386837219-d7a80738-588a-4146-b769-0fef82243521](https://github.com/user-attachments/assets/78f68424-e29b-4936-9ce9-8bf3a7357f80)
目前Ubuntu浏览器可以正常外网，终端普通用户和root用户均可curl外网。
2024年11月16日21:30
添加了telegram的proxy，后不报上述错误，但有新的错误：telebot: unexpected end of JSON input
![image](https://github.com/user-attachments/assets/17115058-a1c6-49b6-a6b5-29ec7db89bd0)

**Comment by assimon** [comment]
> 2024年11月16日上午： 在虚拟机ubuntu系统中安装了docker compose，目前一直卡在“无法找到镜像”，添加国内镜像到daemon.json也不行； 虚拟机通过桥接可以连外网，docker info显示桥接配置也正确。但docker run hello-world一直提示找不到镜像。 2024年11月16日18:00 更换了新的镜像链接，成功运行，但是又有新问题：一直提示 telebot: Post "https://api.telegram.org/bot7**************/getMe": dial tcp 199.96.63.53:443: i/o timeout ![386837219-d7a80738-588a-4146-b769-0fef82243521](https://private-user-images.githubusercontent.com/52785767/386837708-78f68424-e29b-4936-9ce9-8bf3a7357f80.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyNTEzNTIsIm5iZiI6MTczMjI1MTA1MiwicGF0aCI6Ii81Mjc4NTc2Ny8zODY4Mzc3MDgtNzhmNjg0MjQtZTI5Yi00OTM2LTljZTktOGJmM2E3MzU3ZjgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIyVDA0NTA1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzNWYxNGFhZjQ0MTY4Y2ZlMmJjZmY5MjhmOWVkMzY3N2JhYjI5ZjA2NzQ0ZjZiMzUzMzU5MDA2ZGUyODcwN2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3pKVvxC2GmygWl5k53TQ8KONBT7A9XFKT_h0EDGLM7Q) 目前Ubuntu浏览器可以正常外网，终端普通用户和root用户均可curl外网。 2024年11月16日21:30 添加了telegram的proxy，后不报上述错误，但有新的错误：telebot: unexpected end of JSON input ![image](https://private-user-images.githubusercontent.com/52785767/386848840-17115058-a1c6-49b6-a6b5-29ec7db89bd0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyNTEzNTIsIm5iZiI6MTczMjI1MTA1MiwicGF0aCI6Ii81Mjc4NTc2Ny8zODY4NDg4NDAtMTcxMTUwNTgtYTFjNi00OWI2LWE2YjUtMjllYzdkYjg5YmQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIyVDA0NTA1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkMTUwMzAyMThiOTIzOWE2YzY1MDIzNTU5OWIyNjE4NWFmODBlNDEzZGUwYWIwYzE0NWFlM2M5ZDY3NGM2NjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gSEHU1AJ50l7yDOH3XcP8O9HrDkTCmkAIiAPkePTw5g)

telegram的api需要境外服务器才行，被墙了的
